### ISSUE TITLE
trying to find README file by a python script which is not present

### ISSUE THREAD

**Issue by maamirs** [markoshorro/gem5#4]
while building it using SCONS an error comes out:
"scons: *** [build/X86/python/m5/info.py] Source `README' not found, needed by target `build/X86/python/m5/info.py'.
scons: building terminated because of errors"

the file info.py doesn't exist in that directory, 
Can some one point out as to why this is an issue

**Comment by maamirs** [comment]
this issue can easily be fixed by just copying the orignal README file to the root directory from the orignal  gem5 simulator, the author had modified the README(README to README.MD) file extension, that's why it was giving an error

**Comment by tuvaluhk** [comment]
coooolll
