### ISSUE TITLE
How to build gem5-spm?

### ISSUE THREAD

**Issue by kidist-123** [markoshorro/gem5#6]
Hi, I am Kidist A.
I am using your gem5-spm for my research about scratchpad memory.
I just cloned the code and tried to build it and got an error :

```

/gem5-spm# scons build/X86/gem5.opt -j4
scons: Reading SConscript files ...
ImportError: cannot import name 'attrdict' from 'attrdict' (/usr/local/lib/python3.8/dist-packages/attrdict/__init__.py):
  File "/home/kidist/gem5-spm/SConstruct", line 134:
    from m5.util import compareVersions, readCommand
  File "/home/kidist/gem5-spm/src/python/m5/util/__init__.py", line 37:
    from attrdict import attrdict, multiattrdict, optiondict

```
I installed 'attrdict' but could not resolve it.

Thank you!

**Comment by markoshorro** [comment]
Hey @kidist-123, I'm sorry but this project is no longer being maintained.

I recommend you to go through the commits I did here and check if the changes can be applied to a new version of the gem5 project.
